- name: SSH Connection (Tạm dừng để kiểm tra)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false # Chuyển thành false để không bị chặn do lỗi xác thực
        install-dependencies: false
        tmate-server-host: ssh.tmate.io
