- name: Install tmate
      run: |
        sudo apt-get update
        sudo apt-get install -y tmate

    - name: SSH Connection (Tạm dừng để kiểm tra)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
        install-dependencies: false
        tmate-server-host: ssh.tmate.io
